In [190]:
import numpy as np
from scipy.special import expit as activation_function
from scipy.stats import truncnorm

In [191]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt


In [192]:
data = pd.read_csv("C:/Users/sirid/OneDrive/Documents/ML/data_num.csv")
df = pd.read_csv("C:/Users/sirid/OneDrive/Documents/ML/data_mixed.csv")

In [193]:
data

host_listings_count  host_verifications  accommodates  bathrooms  \
0                       6                   6             4        1.0   
1                       2                   5             6        2.0   
2                       5                   7             2        1.0   
3                       6                   6             4        1.0   
4                       1                   5             2        1.0   
...                   ...                 ...           ...        ...   
1157                    1                   5             2        1.0   
1158                    1                   6             6        1.0   
1159                    2                   4             6        2.0   
1160                    1                   5             5        1.0   
1161                    1                   5             4        1.0   

      bedrooms  price  security_deposit  cleaning_fee  extra_people  \
0          1.0    150               100            40             0   
1          3.0    450               700           125            15   
2          1.0     60               150            25             0   
3          1.0    150               100            40             0   
4          1.0     99               500           150             0   
...        ...    ...               ...           ...           ...   
1157       0.0    125               150            45             0   
1158       2.0    100               200            89            20   
1159       3.0    175               500            95            30   
1160       2.0    154               150            85            50   
1161       1.0     79               500            50            25   

      minimum_nights  availability_365  number_of_reviews  \
0                  2               291                 43   
1                  1               365                 38   
2                  2               100                173   
3                  2               324                 32   
4                  3               229                  8   
...              ...               ...                ...   
1157               2               358                 12   
1158               2               329                 10   
1159               3               294                 29   
1160               2               227                  5   
1161               2               273                  2   

      review_scores_rating  review_scores_cleanliness  reviews_per_month  
0                     96.0                       10.0               1.48  
1                     92.0                        9.0               0.89  
2                     97.0                       10.0               4.73  
3                     97.0                       10.0               1.55  
4                     97.0                       10.0               0.98  
...                    ...                        ...                ...  
1157                  95.0                       10.0               2.34  
1158                  98.0                       10.0               3.95  
1159                  96.0                        9.0               1.15  
1160                  92.0                        8.0               1.56  
1161                 100.0                       10.0               2.00  

[1162 rows x 15 columns]

In [194]:
#!pip install tensorflow

In [195]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from tensorflow.math import confusion_matrix

In [196]:
target_column = ['room_type'] 
predictors = list(set(list(data.columns)))
data[predictors] = data[predictors]/data[predictors].max()
data.describe()

host_listings_count  host_verifications  accommodates    bathrooms  \
count          1162.000000         1162.000000   1162.000000  1162.000000   
mean              0.120482            0.609294      0.243599     0.290113   
std               0.209594            0.129789      0.139607     0.139352   
min               0.027027            0.250000      0.062500     0.111111   
25%               0.027027            0.500000      0.125000     0.222222   
50%               0.054054            0.625000      0.250000     0.222222   
75%               0.108108            0.750000      0.312500     0.333333   
max               1.000000            1.000000      1.000000     1.000000   

          bedrooms        price  security_deposit  cleaning_fee  extra_people  \
count  1162.000000  1162.000000       1162.000000   1162.000000    1162.00000   
mean      0.238669     0.228046          0.110237      0.222762       0.05812   
std       0.165524     0.145099          0.092078      0.156830       0.07142   
min       0.000000     0.046667          0.038000      0.016667       0.00000   
25%       0.166667     0.141667          0.060000      0.116667       0.00000   
50%       0.166667     0.190000          0.080000      0.166667       0.04400   
75%       0.333333     0.258333          0.120000      0.296667       0.10000   
max       1.000000     1.000000          1.000000      1.000000       1.00000   

       minimum_nights  availability_365  number_of_reviews  \
count     1162.000000       1162.000000        1162.000000   
mean         0.071484          0.691272           0.094095   
std          0.065199          0.326494           0.117678   
min          0.032258          0.000000           0.003597   
25%          0.032258          0.421918           0.017986   
50%          0.064516          0.843836           0.050360   
75%          0.096774          0.980822           0.118705   
max          1.000000          1.000000           1.000000   

       review_scores_rating  review_scores_cleanliness  reviews_per_month  
count           1162.000000                1162.000000        1162.000000  
mean               0.943434                   0.957229           0.185298  
std                0.070672                   0.077783           0.153203  
min                0.200000                   0.400000           0.002725  
25%                0.930000                   0.900000           0.070163  
50%                0.960000                   1.000000           0.139419  
75%                0.990000                   1.000000           0.266803  
max                1.000000                   1.000000           1.000000

In [197]:
df['room_type'] = df['room_type'].astype('category')
# Assigning numerical values and storing in another column
df['room_type'] = df['room_type'].cat.codes

In [198]:
y = df['room_type'].values
X = data

In [199]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=40)
print(X_train.shape); print(X_test.shape)

(813, 15)
(349, 15)


In [200]:
y_train = to_categorical(y_train, 3)
y_test = to_categorical(y_test, 3)

In [201]:
model = Sequential()
model.add(Dense(15, input_dim=15, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [202]:
model.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])

In [203]:
model.fit(X_train, y_train, epochs=25)

Epoch 1/25
26/26 [==============================] - 3s 3ms/step - loss: 1.0840 - accuracy: 0.5117
Epoch 2/25
26/26 [==============================] - 0s 4ms/step - loss: 0.9972 - accuracy: 0.7934
Epoch 3/25
26/26 [==============================] - 0s 4ms/step - loss: 0.8630 - accuracy: 0.7934
Epoch 4/25
26/26 [==============================] - 0s 4ms/step - loss: 0.6980 - accuracy: 0.7934
Epoch 5/25
26/26 [==============================] - 0s 4ms/step - loss: 0.5948 - accuracy: 0.7934
Epoch 6/25
26/26 [==============================] - 0s 4ms/step - loss: 0.5694 - accuracy: 0.7934
Epoch 7/25
26/26 [==============================] - 0s 3ms/step - loss: 0.5549 - accuracy: 0.7934
Epoch 8/25
26/26 [==============================] - 0s 4ms/step - loss: 0.5379 - accuracy: 0.7934
Epoch 9/25
26/26 [==============================] - 0s 3ms/step - loss: 0.5181 - accuracy: 0.7934
Epoch 10/25
26/26 [==============================] - 0s 4ms/step - loss: 0.5014 - accuracy: 0.7934
Epoch 11/25
26/26 [

In [204]:
pred_train= model.predict(X_train)
scores = model.evaluate(X_train, y_train, verbose=0)
print('Accuracy on training data: {}% \n Error on training data: {}'.format(scores[1], 1 - scores[1]))   
 
pred_test= model.predict(X_test)
scores2 = model.evaluate(X_test, y_test, verbose=0)
print('Accuracy on test data: {}% \n Error on test data: {}'.format(scores2[1], 1 - scores2[1]))    

26/26 [==============================] - 0s 3ms/step
Accuracy on training data: 0.8733087182044983% 
 Error on training data: 0.1266912817955017
11/11 [==============================] - 0s 3ms/step
Accuracy on test data: 0.9111747741699219% 
 Error on test data: 0.08882522583007812


In [205]:
y_test

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [206]:
pred_test

array([[8.6773062e-01, 1.2886605e-01, 3.4033146e-03],
       [2.0420638e-01, 7.7457619e-01, 2.1217518e-02],
       [9.6722901e-01, 3.1802829e-02, 9.6816197e-04],
       ...,
       [9.5552069e-01, 4.3253608e-02, 1.2256620e-03],
       [9.9365121e-01, 6.2078657e-03, 1.4095813e-04],
       [9.8234010e-01, 1.7106380e-02, 5.5356976e-04]], dtype=float32)

In [207]:
row_maxes = pred_test.max(axis=1).reshape(-1, 1)
np.where(pred_test == row_maxes, 1, 0)
#np.where(pred_test == row_maxes).astype(int)

array([[1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       ...,
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0]])

In [208]:
pred_test[:] = np.where(pred_test == row_maxes, 1, 0)

In [209]:
pred_test

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [210]:
pred_test = pd.DataFrame(pred_test, columns = [0,1,2])
y_test = pd.DataFrame(y_test, columns = [0,1,2]) 

In [211]:
pred = pred_test.idxmax(1)
y_test_array = y_test.idxmax(1)

In [212]:
print("confusion matrix : ", confusion_matrix(y_test_array,pred))


confusion matrix :  tf.Tensor(
[[280   2   0]
 [ 27  33   0]
 [  1   1   5]], shape=(3, 3), dtype=int32)


In [213]:
data

host_listings_count  host_verifications  accommodates  bathrooms  \
0                0.162162               0.750        0.2500   0.222222   
1                0.054054               0.625        0.3750   0.444444   
2                0.135135               0.875        0.1250   0.222222   
3                0.162162               0.750        0.2500   0.222222   
4                0.027027               0.625        0.1250   0.222222   
...                   ...                 ...           ...        ...   
1157             0.027027               0.625        0.1250   0.222222   
1158             0.027027               0.750        0.3750   0.222222   
1159             0.054054               0.500        0.3750   0.444444   
1160             0.027027               0.625        0.3125   0.222222   
1161             0.027027               0.625        0.2500   0.222222   

      bedrooms     price  security_deposit  cleaning_fee  extra_people  \
0     0.166667  0.250000              0.04      0.133333          0.00   
1     0.500000  0.750000              0.28      0.416667          0.06   
2     0.166667  0.100000              0.06      0.083333          0.00   
3     0.166667  0.250000              0.04      0.133333          0.00   
4     0.166667  0.165000              0.20      0.500000          0.00   
...        ...       ...               ...           ...           ...   
1157  0.000000  0.208333              0.06      0.150000          0.00   
1158  0.333333  0.166667              0.08      0.296667          0.08   
1159  0.500000  0.291667              0.20      0.316667          0.12   
1160  0.333333  0.256667              0.06      0.283333          0.20   
1161  0.166667  0.131667              0.20      0.166667          0.10   

      minimum_nights  availability_365  number_of_reviews  \
0           0.064516          0.797260           0.154676   
1           0.032258          1.000000           0.136691   
2           0.064516          0.273973           0.622302   
3           0.064516          0.887671           0.115108   
4           0.096774          0.627397           0.028777   
...              ...               ...                ...   
1157        0.064516          0.980822           0.043165   
1158        0.064516          0.901370           0.035971   
1159        0.096774          0.805479           0.104317   
1160        0.064516          0.621918           0.017986   
1161        0.064516          0.747945           0.007194   

      review_scores_rating  review_scores_cleanliness  reviews_per_month  
0                     0.96                        1.0           0.134423  
1                     0.92                        0.9           0.080836  
2                     0.97                        1.0           0.429609  
3                     0.97                        1.0           0.140781  
4                     0.97                        1.0           0.089010  
...                    ...                        ...                ...  
1157                  0.95                        1.0           0.212534  
1158                  0.98                        1.0           0.358765  
1159                  0.96                        0.9           0.104450  
1160                  0.92                        0.8           0.141689  
1161                  1.00                        1.0           0.181653  

[1162 rows x 15 columns]